name: Build ZMK Firmware

on:
  push:
  pull_request:

jobs:
  build:
    name: Build user config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout user config
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install west
        run: pip install --upgrade west

      - name: West init
        run: |
          rm -rf config/.west
          west init -m https://github.com/zmkfirmware/zmk.git --mr main config

      - name: West update
        run: west update

      - name: Export ZEPHYR_BASE
        run: echo "ZEPHYR_BASE=$(pwd)/zmk/zephyr" >> $GITHUB_ENV

      - name: Build (left)
        run: west build -s zmk/app -d build/left -b nice_nano -- -DSHIELD=charybdis_4x6_left

      - name: Build (right)
        run: west build -s zmk/app -d build/right -b nice_nano -- -DSHIELD=charybdis_4x6_right

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2
